server:
  port: 8081

spring:
  application:
    name: ms-auth
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/erp_central?ApplicationName=CentralPool-MS-AUTH
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    open-in-view: false

app:
  tenant:
    default-db-user: ${TENANT_DB_USER:admin}
    default-db-password: ${TENANT_DB_PASSWORD:admin_password}
    datasource:
      base-url: jdbc:postgresql://localhost:5433/
      username: ${DB_USER:admin}
      password: ${DB_PASSWORD:admin_password}
  kafka:
    topics:
      user-events: "auth.user.events"
    groups:
      user-sync: "kafka-group.auth.user-sync"



application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
